package cl.segfault.coffeessh.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme
val LightPrimary = Color(0xFF6F4E37) // coffee
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFF0DCC9) // latte foam
val LightOnPrimaryContainer = Color(0xFF271405)
val LightSecondary = Color(0xFF635244)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE9DDD0)
val LightOnSecondaryContainer = Color(0xFF211A12)
val LightTertiary = Color(0xFF9C6F3E) // caramel
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDCBE)
val LightOnTertiaryContainer = Color(0xFF331F00)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFFF8F4)
val LightOnBackground = Color(0xFF211A15)
val LightSurface = Color(0xFFFFF8F4)
val LightOnSurface = Color(0xFF211A15)
val LightSurfaceVariant = Color(0xFFF0E0D2)
val LightOnSurfaceVariant = Color(0xFF4F4539)
val LightOutline = Color(0xFF817468)
val LightOutlineVariant = Color(0xFFD4C4B5)
val LightScrim = Color(0xFF000000)
val LightInverseSurface = Color(0xFF362F29)
val LightInverseOnSurface = Color(0xFFFBEFE7)
val LightInversePrimary = Color(0xFFE5C29F)
val LightSurfaceDim = Color(0xFFE4D8CD)
val LightSurfaceBright = Color(0xFFFFF8F4)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFFAF2EA)
val LightSurfaceContainer = Color(0xFFF4ECE2)
val LightSurfaceContainerHigh = Color(0xFFEEE6DC)
val LightSurfaceContainerHighest = Color(0xFFE8E0D6)

// Dark scheme
val DarkPrimary = Color(0xFFE5C29F) // cream coffee
val DarkOnPrimary = Color(0xFF422B15)
val DarkPrimaryContainer = Color(0xFF5A4028)
val DarkOnPrimaryContainer = Color(0xFFF0DCC9)
val DarkSecondary = Color(0xFFCDB8A5)
val DarkOnSecondary = Color(0xFF34281B)
val DarkSecondaryContainer = Color(0xFF4B3D2F)
val DarkOnSecondaryContainer = Color(0xFFE9DDD0)
val DarkTertiary = Color(0xFFE5BE8B)
val DarkOnTertiary = Color(0xFF452B00)
val DarkTertiaryContainer = Color(0xFF7C5528)
val DarkOnTertiaryContainer = Color(0xFFFFDCBE)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF1A120C)
val DarkOnBackground = Color(0xFFF0E0D5)
val DarkSurface = Color(0xFF1A120C)
val DarkOnSurface = Color(0xFFF0E0D5)
val DarkSurfaceVariant = Color(0xFF4F4539)
val DarkOnSurfaceVariant = Color(0xFFD4C4B5)
val DarkOutline = Color(0xFF9C8E80)
val DarkOutlineVariant = Color(0xFF4F4539)
val DarkScrim = Color(0xFF000000)
val DarkInverseSurface = Color(0xFFF0E0D5)
val DarkInverseOnSurface = Color(0xFF362F29)
val DarkInversePrimary = Color(0xFF6F4E37)
val DarkSurfaceDim = Color(0xFF1A120C)
val DarkSurfaceBright = Color(0xFF423830)
val DarkSurfaceContainerLowest = Color(0xFF140D08)
val DarkSurfaceContainerLow = Color(0xFF221A13)
val DarkSurfaceContainer = Color(0xFF271E17)
val DarkSurfaceContainerHigh = Color(0xFF322921)
val DarkSurfaceContainerHighest = Color(0xFF3D332B)
